// Code generated by Thrift Compiler (0.15.0). DO NOT EDIT.

package header

import (
	"bytes"
	"context"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"dm/datatype"
	"dm/deviceusage"
	"dm/hostservermanagement"
	"dm/projectmanagement"
	"dm/rundata"
	"dm/runmanagement"
	"dm/runplan"
	"dm/runresult"
	"dm/runtask"
	"dm/sampleinfo"
	"dm/servermanagement"
	"dm/devicemanagement"
	"dm/runningtask"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = datatype.GoUnusedProtection__
var _ = deviceusage.GoUnusedProtection__
var _ = hostservermanagement.GoUnusedProtection__
var _ = projectmanagement.GoUnusedProtection__
var _ = rundata.GoUnusedProtection__
var _ = runmanagement.GoUnusedProtection__
var _ = runplan.GoUnusedProtection__
var _ = runresult.GoUnusedProtection__
var _ = runtask.GoUnusedProtection__
var _ = sampleinfo.GoUnusedProtection__
var _ = servermanagement.GoUnusedProtection__
var _ = devicemanagement.GoUnusedProtection__
var _ = runningtask.GoUnusedProtection__

func init() {
}

